addSbtPlugin("com.47deg"                 % "sbt-microsites"           % "0.7.18")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"           % "1.3.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"              % "0.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.8")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "0.6.28")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"            % "1.5.1")
