addSbtPlugin("com.jsuereth"      % "sbt-pgp"        % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"    % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"   % "0.5.0")
addSbtPlugin("com.fortysevendeg" % "sbt-microsites" % "0.3.1")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"    % "0.6.18")
addSbtPlugin("org.tpolecat"      % "tut-plugin"     % "0.4.6")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "1.5.0")
